spring:
  profiles:
    active: test
    include: swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.3.3:3306/yunche_test?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    name:
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 50
  rabbitmq:
    username: yunche
    password: 123456
    host: 192.168.3.2
    virtual-host: yunche
    port: 5672
  redis:
    database: 10
    host: 192.168.3.2
    port: 6379
    password: redis123456
  boot:
    admin:
      client:
        url: http://localhost:10762
  jpa:
    #    hibernate:
    #     ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 250
      hibernate.jdbc.time_zone: Asia/Shanghai
      hibernate.enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    elasticsearch:
      cluster-nodes: 192.168.3.32:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: ["http://192.168.3.32:9200"]
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: domain-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10761/eureka/
server:
  port: 10003
#合同下载pdf路径
pdffile:
  dir: /usr/local/files/PDF
  base-url: http://192.168.3.3:10000/domain-service/api/templateController/getContractInfoPdfById
#还款申请API接口,收款账户动态获取API接口
repaymentApplyApi:
  applyUrl: http://25003uc531.qicp.vip/due/collection/saveRepaymentRecord
  receiveAccountUrl: http://25003uc531.qicp.vip/due/collection/listGatheringAccountConfigInfo
